extends:
  - eslint:recommended
  - plugin:react/recommended
settings:
  react:
    version: detect
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
env:
  node: true
  browser: true
rules:
  no-unused-vars: 1
